name: devsecops-security-pipeline

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  trivy_image_scan:
    name: Build Docker image + Trivy scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t devsecops-demo:${{ github.sha }} .

      - name: Trivy scan (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: devsecops-demo:${{ github.sha }}
          format: table
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
